---   
- name: Deploy Container on proxmox
  hosts: proxmox
  become: false
  tasks:
    - name: Install pip
      ansible.builtin.package:
        name:
          - python3-pip
          - python3-proxmoxer
        state: present
        
    - name: Create a new LXC container
      community.general.proxmox:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user_api }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
        ostemplate: "{{ container_template }}"
        hostname: "{{ hostname }}"
        password: "{{ container_root_password }}"
        


