---   
- name: Deploy Container on proxmox
  hosts: localhost
  become: false
  tasks:
    - name: Create a new LXC container
      community.general.proxmox:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        
        ostemplate: 'local:vztmpl/ubuntu-14.04-x86_64.tar.gz'
        hostname: "{{ hostname }}"
        password: "{{ container_root_password }}"
        


