---
- hosts: all
  
  become: true
  gather_facts: false
  tasks:
    - name: Create User
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        password: "{{ userpass | password_hash('sha512') }}"
        update_password: on_create
      #  groups: "{{ super_group }}"
        append: yes
        
   - name: "check or change /home/{{ username }}"
      file:
        path: /home/{{ username }}
        state: touch
        mode: '700'
        
    - name: "check or change /home/{{ username }}/.ssh/authorized_keys"
      file:
        path: /home/{{ username }}/.ssh/authorized_keys
        state: touch
        mode: '644'

    - name: Set authorized key
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ item }}"
      loop:
        - "{{ key }}"
