---
- hosts: all
  
  become: true
  gather_facts: false
  tasks:
    - name: Install required packaged
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - acl
        - python3-pip
        
    - name: Create User
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash
        password: "{{ userpass | password_hash('sha512') }}"
        update_password: on_create
      #  groups: "{{ super_group }}"
        append: yes

    - name: Set authorized key
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ item }}"
      loop:
        - "{{ key }}"

    - name: Creating a file with content
      copy:
        dest: "/etc/sudoers.d/{{ username }}"
        content: |
          {{ username }} ALL=(ALL) NOPASSWD: ALL

        
    - name: Create a new file with permissions
      file:
        path: "/etc/sudoers.d/{{ username }}"
        state: touch
        mode: 0440
        owner: root
